name: test-gh
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.16"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Install Carvel Tools
      uses: vmware-tanzu/carvel-setup-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        only: ytt
        ytt: v0.34.0
    - name: Run Tests
      run: |
        set -e -x

        export GOPATH=$(pwd)
        cd src/github.com/${{ github.repository }}

        mkdir -p /tmp/bin
        export PATH=/tmp/bin:$PATH

        wget -O- https://github.com/kubernetes/minikube/releases/download/v1.10.0/minikube-linux-amd64 > /tmp/bin/minikube
        echo "9d34cb50bc39f80d39f92d1fb7cb23a271504b519f5e805574894d395ce3e7b3  /tmp/bin/minikube" | sha256sum -c -
        chmod +x /tmp/bin/minikube
        minikube start --driver=docker
        eval $(minikube docker-env --shell=bash)

        ./hack/build-binaries.sh

        export KAPP_E2E_NAMESPACE=kapp-test
        kubectl create ns $KAPP_E2E_NAMESPACE

        ./hack/test-all.sh
